---
# List of custom programs to install that are not packaged. These each require
# a install_name function in the appropriate place in the 'custom' directory to
# define the steps for downloading, building, and installing the package.
bio_general:
 #- bio4j # no easy download for 0.8
 - anaconda
 - emboss
 - pgdspider
bio_nextgen:
  alignment:
    - bwa
    - bowtie
    - bowtie2
    - gmap
    - lastz
    - mosaik
    # - perm # difficult build process with directory names
    - snap
    - star
    #- stampy # no version names on tarballs
  utilities:
    - bamtools
    - bedtools
    - cram
    - dwgsim
    - fastqc
    - fastq_screen
    - fastx_toolkit
    - ogap
    - rnaseqc
    # - solexaqa
    - varianttools
    - vcftools
  analysis:
    - cufflinks
    # - echo # build problems on ubuntu 12.10
    - picard
    - samtools
    - sambamba
    - shrec
    - tophat
    # - vep # lots of timeout failures on download
  assembly:
    - abyss
    - cortex_var
    - ray
    - transabyss
    - trinity
    - velvet
  sv:
    - delly
    - hydra
    - lumpy
    - freec
  variant:
    - bcbio_variation
    - crisp
    - freebayes
    - gatk
    - gemini
    - grabix
    - mutect
    - tabix
    - tassel
    - snpeff
    - stacks
    - varscan
    - vcflib
  chip:
    - macs
  needs_64bit:
    - ucsc_tools
    - bfast
    - novoalign
    - novosort
    - plink_seq
bio_proteomics:
  - transproteomic_pipeline
  - omssa
  - mzmine
  - myrimatch
  - directag
  - tagrecon
  - idpqonvert
  - pepitome
  - percolator
bio_proteomics_wine:
  - proteomics_wine_env
  #- multiplierz
  - proteowizard
  - morpheus
cloudman:
  - nginx
  - proftpd
  - sge
  - novnc
galaxy:
  - galaxy_webapp
galaxy_tools:
  - cbl_galaxy_tools
galaxyp:
  - galaxy_protk
  - protvis
distributed:
  - gnu_parallel
  - pydoop
  - seal
system:
  - s3fs
python:
  - bx-python
  - netsa-python
  - rpy
java:
  - leiningen
phylogeny:
  - tracer
  - beast
#Viral Cloud Resource (VCR) - JCVI's Viral Genomic Pipelines on the cloud
vcr:
  - viralassembly
  - viralassembly_cleanall
  - viralvigor
  - viralvigor_test
  - viralvigor_validate
  - viralvigor_cleanall
# ToDo -- test on 64bit with bfast
#- dnaa
#- srma
