---
# List of custom programs to install that are not packaged. These each require 
# a install_name function in the appropriate place in the 'custom' directory to
# define the steps for downloading, building, and installing the package.
bio_general:
 - bio4j
 - emboss
 - pgdspider
bio_nextgen:
  alignment:
    - bwa
    - bowtie
    - bowtie2
    - gmap
    - lastz
    - mosaik
    - perm
    - stampy
  utilitites:
    - bedtools
    - dwgsim
    - fastqc
    - fastx_toolkit
    - solexaqa
    - varianttools
    - vcftools
  analysis:
    - cufflinks
    - echo
    - freebayes
    - gatk
    - gatk_queue
    - picard
    - samtools
    - shrec
    - snpeff
    - tophat
  assembly:
    - abyss
    - transabyss
    - trinity
    - velvet
  sv:
    - hydra
  variant:
    - crisp
    - tassel
    - stacks
  chip:
    - macs
  needs_64bit:
    - ucsc_tools
    - bfast
    - novoalign
    - plink_seq
cloudman:
  - nginx
  - proftpd
  - sge
distributed:
  - mahout
  - pydoop
python:
  - bx-python
  - matplotlib
  - rpy
java:
  - leinengin
phylogeny:
  - tracer
  - beast
  #- cljr
# ToDo -- test on 64bit with bfast
#- dnaa
#- srma
