# Packages available in the Homebrew and Linuxbrew package manager
---
bio_nextgen:
  alignment:
    - bwa
    - bowtie2
    - novoalign
    - rna-star
  utilities:
    - bamtools
    - bedtools
    - cramtools
    - biobambam
    - fastqc
    - fastx_toolkit
    - qualimap
    - sambamba-binary
    - staden_io_lib
  analysis:
    - cufflinks-binary
    - samtools
    - htslib
    - bcftools
    #- tophat
  variant:
    - delly;--with-binary
    - freebayes
    - gatk-framework
    - lofreq
    - lumpy-sv
    - pindel
    - platypus-variant
    - rtg-tools
    - scalpel
    - snpeff
    - theta2
    - vardict
    - vcflib
    - vcftools
    - vep
    - wham
    # - yaha  The Principal Investigator has moved; the software does not download ATM
distributed:
  - parallel
