---
# Configuration file defining R specific libraries that are installed 
# via CRAN and Bioconductor.
cranrepo: http://software.rc.fas.harvard.edu/mirrors/R/
cran:
 - abind
 - ape
 - aplpack
 - biglm
 - BiodiversityR
 - bitops
 - boot
 - car
 - caTools
 - chron
 - class
 - cluster
 - codetools
 - coin
 - colorspace
 - date
 - DBI
 - digest
 - effects
 - flashClust
 - foreign
 - gdata
 - gee
 - graph
 - ggplot2
 - gplots
 - gtools
 - hdf5
 - hexbin
 - hmisc
 - HH
 - hwriter
 - kernlab
 - kernsmooth
 - lattice
 - latticeExtra
 - leaps
 - lmtest
 - maptree
 - mass
 - matrix
 - mclust
 - mgcv
 - modeltools
 - multcomp
 - multicore
 - nlme
 - NMF
 - nnet
 - pamr
 - pi0
 - plotrix
 - plyr
 - proto
 - qvalue
 - rcmdr
 - relimp
 - reshape
 - rgl
 - RColorBrewer
 - RCurl
 - rpart
 - rjson
 - Rmpi
 - RSQLite
 - sandwich
 - sm
 - snowfall
 - spatial
 - sqldf
 - statmod
 - strucchange
 - survival
 - vegan
 - vgam
 - vr
 - XML
 - xtable
 - yacca
 - zoo

biocrepo: http://bioconductor.org/biocLite.R
bioc:
 - affy
 - affydata
 - affyio
 - affyPLM
 - affyQCReport
 - annaffy
 - annotate
 - AnnotationDbi
 - ArrayExpress
 - arrayQualityMetrics
 - ArrayTools
 - BayesPeak
 - baySeq
 - beadarray
 - Biobase
 - BiocInstaller
 - bioDist
 - biomaRt
 - Biostrings
 - BSgenome
 #- BSgenome.Athaliana.TAIR.TAIR9
 #- BSgenome.Celegans.UCSC.ce6
 #- BSgenome.Dmelanogaster.UCSC.dm3
 #- BSgenome.Hsapiens.UCSC.hg19
 #- BSgenome.Mmusculus.UCSC.mm9
 #- BSgenome.Scerevisiae.UCSC.sacCer2
 - ChIPpeakAnno
 - chipseq
 - ChIPseqR
 - ChIPsim
 - CNAnorm
 - cn.mops
 - CSAR
 - cummeRbund
 - DEGseq
 - DESeq
 - DEXSeq
 - DiffBind
 - DynDoc
 - edgeR
 - EDASeq
 - exomeCopy
 - gage
 - gcrma
 - genefilter
 - geneplotter
 - GenomicFeatures
 - GenomicRanges
 - GEOquery
 - girafe
 - GGBase
 - GGtools
 - globaltest
 #- GO.db
 - GOFunction
 - goseq
 - GOstats
 - GSEABase
 - GWASTools
 - hgu95av2.db
 - HilbertVis
 - htSeqTools
 - IRanges
 - KEGG.db
 - limma
 - lumi
 - makecdfenv
 - marray
 - MEDIPS
 - multtest
 - MotIV
 - oneChannelGUI
 #- org.At.tair.db
 #- org.Ce.eg.db
 #- org.Dm.eg.db
 #- org.Hs.eg.db
 #- org.Mm.eg.db
 #- org.Sc.sgd.db
 #- org.Xl.eg.db
 - preprocessCore
 - PICS
 - rGADEM
 - R453Plus1Toolbox
 - rGADEM
 - Rgraphviz
 - rnaSeqMap
 - Rolexa
 - Rsamtools
 - rtracklayer
 - segmentSeq
 - ShortRead
 - siggenes
 - simpleaffy
 - snpMatrix
 - splots
 - SRAdb
 - vsn
